services:
  telegram-bot-kiosk:
    build: .
    volumes:
      - ./database.db:/app/database.db
    #      - ./log/debug.log:/app/log/debug.log
    container_name: telegram-bot-kiosk
    restart: unless-stopped
    ports:
      - "80:2222"
    env_file:
      - .env
    deploy:
      resources:
        limits: # жёсткие лимиты
          cpus: '1'      # 2 ядра CPU
          memory: 512M       # 4 ГБ RAM
        reservations: # мягкие параметры
          cpus: '0.5'      # Минимум 1 ядро
          memory: 256M       # Минимум 2 ГБ
    cpuset: "12"  # Ядра 14 и 15